/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.example.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CheckTransactionEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2359446997712605731L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CheckTransactionEvent\",\"namespace\":\"org.example.events\",\"fields\":[{\"name\":\"phoneNumber\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"transactionNumber\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"amount\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":16,\"scale\":2}},{\"name\":\"owner\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<CheckTransactionEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CheckTransactionEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CheckTransactionEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CheckTransactionEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CheckTransactionEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CheckTransactionEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CheckTransactionEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CheckTransactionEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CheckTransactionEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String phoneNumber;
  private java.lang.String transactionNumber;
  private java.math.BigDecimal amount;
  private java.lang.String owner;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CheckTransactionEvent() {}

  /**
   * All-args constructor.
   * @param phoneNumber The new value for phoneNumber
   * @param transactionNumber The new value for transactionNumber
   * @param amount The new value for amount
   * @param owner The new value for owner
   */
  public CheckTransactionEvent(java.lang.String phoneNumber, java.lang.String transactionNumber, java.math.BigDecimal amount, java.lang.String owner) {
    this.phoneNumber = phoneNumber;
    this.transactionNumber = transactionNumber;
    this.amount = amount;
    this.owner = owner;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return phoneNumber;
    case 1: return transactionNumber;
    case 2: return amount;
    case 3: return owner;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      new org.apache.avro.Conversions.DecimalConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: phoneNumber = value$ != null ? value$.toString() : null; break;
    case 1: transactionNumber = value$ != null ? value$.toString() : null; break;
    case 2: amount = (java.math.BigDecimal)value$; break;
    case 3: owner = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'phoneNumber' field.
   * @return The value of the 'phoneNumber' field.
   */
  public java.lang.String getPhoneNumber() {
    return phoneNumber;
  }


  /**
   * Sets the value of the 'phoneNumber' field.
   * @param value the value to set.
   */
  public void setPhoneNumber(java.lang.String value) {
    this.phoneNumber = value;
  }

  /**
   * Gets the value of the 'transactionNumber' field.
   * @return The value of the 'transactionNumber' field.
   */
  public java.lang.String getTransactionNumber() {
    return transactionNumber;
  }


  /**
   * Sets the value of the 'transactionNumber' field.
   * @param value the value to set.
   */
  public void setTransactionNumber(java.lang.String value) {
    this.transactionNumber = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public java.math.BigDecimal getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(java.math.BigDecimal value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'owner' field.
   * @return The value of the 'owner' field.
   */
  public java.lang.String getOwner() {
    return owner;
  }


  /**
   * Sets the value of the 'owner' field.
   * @param value the value to set.
   */
  public void setOwner(java.lang.String value) {
    this.owner = value;
  }

  /**
   * Creates a new CheckTransactionEvent RecordBuilder.
   * @return A new CheckTransactionEvent RecordBuilder
   */
  public static org.example.events.CheckTransactionEvent.Builder newBuilder() {
    return new org.example.events.CheckTransactionEvent.Builder();
  }

  /**
   * Creates a new CheckTransactionEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CheckTransactionEvent RecordBuilder
   */
  public static org.example.events.CheckTransactionEvent.Builder newBuilder(org.example.events.CheckTransactionEvent.Builder other) {
    if (other == null) {
      return new org.example.events.CheckTransactionEvent.Builder();
    } else {
      return new org.example.events.CheckTransactionEvent.Builder(other);
    }
  }

  /**
   * Creates a new CheckTransactionEvent RecordBuilder by copying an existing CheckTransactionEvent instance.
   * @param other The existing instance to copy.
   * @return A new CheckTransactionEvent RecordBuilder
   */
  public static org.example.events.CheckTransactionEvent.Builder newBuilder(org.example.events.CheckTransactionEvent other) {
    if (other == null) {
      return new org.example.events.CheckTransactionEvent.Builder();
    } else {
      return new org.example.events.CheckTransactionEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for CheckTransactionEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CheckTransactionEvent>
    implements org.apache.avro.data.RecordBuilder<CheckTransactionEvent> {

    private java.lang.String phoneNumber;
    private java.lang.String transactionNumber;
    private java.math.BigDecimal amount;
    private java.lang.String owner;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.example.events.CheckTransactionEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.phoneNumber)) {
        this.phoneNumber = data().deepCopy(fields()[0].schema(), other.phoneNumber);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.transactionNumber)) {
        this.transactionNumber = data().deepCopy(fields()[1].schema(), other.transactionNumber);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.amount)) {
        this.amount = data().deepCopy(fields()[2].schema(), other.amount);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.owner)) {
        this.owner = data().deepCopy(fields()[3].schema(), other.owner);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing CheckTransactionEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(org.example.events.CheckTransactionEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.phoneNumber)) {
        this.phoneNumber = data().deepCopy(fields()[0].schema(), other.phoneNumber);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.transactionNumber)) {
        this.transactionNumber = data().deepCopy(fields()[1].schema(), other.transactionNumber);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.amount)) {
        this.amount = data().deepCopy(fields()[2].schema(), other.amount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.owner)) {
        this.owner = data().deepCopy(fields()[3].schema(), other.owner);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'phoneNumber' field.
      * @return The value.
      */
    public java.lang.String getPhoneNumber() {
      return phoneNumber;
    }


    /**
      * Sets the value of the 'phoneNumber' field.
      * @param value The value of 'phoneNumber'.
      * @return This builder.
      */
    public org.example.events.CheckTransactionEvent.Builder setPhoneNumber(java.lang.String value) {
      validate(fields()[0], value);
      this.phoneNumber = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'phoneNumber' field has been set.
      * @return True if the 'phoneNumber' field has been set, false otherwise.
      */
    public boolean hasPhoneNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'phoneNumber' field.
      * @return This builder.
      */
    public org.example.events.CheckTransactionEvent.Builder clearPhoneNumber() {
      phoneNumber = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'transactionNumber' field.
      * @return The value.
      */
    public java.lang.String getTransactionNumber() {
      return transactionNumber;
    }


    /**
      * Sets the value of the 'transactionNumber' field.
      * @param value The value of 'transactionNumber'.
      * @return This builder.
      */
    public org.example.events.CheckTransactionEvent.Builder setTransactionNumber(java.lang.String value) {
      validate(fields()[1], value);
      this.transactionNumber = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionNumber' field has been set.
      * @return True if the 'transactionNumber' field has been set, false otherwise.
      */
    public boolean hasTransactionNumber() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'transactionNumber' field.
      * @return This builder.
      */
    public org.example.events.CheckTransactionEvent.Builder clearTransactionNumber() {
      transactionNumber = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public java.math.BigDecimal getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public org.example.events.CheckTransactionEvent.Builder setAmount(java.math.BigDecimal value) {
      validate(fields()[2], value);
      this.amount = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public org.example.events.CheckTransactionEvent.Builder clearAmount() {
      amount = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'owner' field.
      * @return The value.
      */
    public java.lang.String getOwner() {
      return owner;
    }


    /**
      * Sets the value of the 'owner' field.
      * @param value The value of 'owner'.
      * @return This builder.
      */
    public org.example.events.CheckTransactionEvent.Builder setOwner(java.lang.String value) {
      validate(fields()[3], value);
      this.owner = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'owner' field has been set.
      * @return True if the 'owner' field has been set, false otherwise.
      */
    public boolean hasOwner() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'owner' field.
      * @return This builder.
      */
    public org.example.events.CheckTransactionEvent.Builder clearOwner() {
      owner = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CheckTransactionEvent build() {
      try {
        CheckTransactionEvent record = new CheckTransactionEvent();
        record.phoneNumber = fieldSetFlags()[0] ? this.phoneNumber : (java.lang.String) defaultValue(fields()[0]);
        record.transactionNumber = fieldSetFlags()[1] ? this.transactionNumber : (java.lang.String) defaultValue(fields()[1]);
        record.amount = fieldSetFlags()[2] ? this.amount : (java.math.BigDecimal) defaultValue(fields()[2]);
        record.owner = fieldSetFlags()[3] ? this.owner : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CheckTransactionEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<CheckTransactionEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CheckTransactionEvent>
    READER$ = (org.apache.avro.io.DatumReader<CheckTransactionEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










