/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.example.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ResultOfCheckingEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4738245656521873859L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ResultOfCheckingEvent\",\"namespace\":\"org.example.events\",\"fields\":[{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"TransactionStatusAvro\",\"symbols\":[\"ACCEPTED\",\"BLOCKED\"]}},{\"name\":\"transactionNumber\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"reason\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ResultOfCheckingEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ResultOfCheckingEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ResultOfCheckingEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ResultOfCheckingEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ResultOfCheckingEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ResultOfCheckingEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ResultOfCheckingEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ResultOfCheckingEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ResultOfCheckingEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private org.example.events.TransactionStatusAvro status;
  private java.lang.String transactionNumber;
  private java.lang.String reason;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ResultOfCheckingEvent() {}

  /**
   * All-args constructor.
   * @param status The new value for status
   * @param transactionNumber The new value for transactionNumber
   * @param reason The new value for reason
   */
  public ResultOfCheckingEvent(org.example.events.TransactionStatusAvro status, java.lang.String transactionNumber, java.lang.String reason) {
    this.status = status;
    this.transactionNumber = transactionNumber;
    this.reason = reason;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return status;
    case 1: return transactionNumber;
    case 2: return reason;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: status = (org.example.events.TransactionStatusAvro)value$; break;
    case 1: transactionNumber = value$ != null ? value$.toString() : null; break;
    case 2: reason = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public org.example.events.TransactionStatusAvro getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(org.example.events.TransactionStatusAvro value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'transactionNumber' field.
   * @return The value of the 'transactionNumber' field.
   */
  public java.lang.String getTransactionNumber() {
    return transactionNumber;
  }


  /**
   * Sets the value of the 'transactionNumber' field.
   * @param value the value to set.
   */
  public void setTransactionNumber(java.lang.String value) {
    this.transactionNumber = value;
  }

  /**
   * Gets the value of the 'reason' field.
   * @return The value of the 'reason' field.
   */
  public java.lang.String getReason() {
    return reason;
  }


  /**
   * Sets the value of the 'reason' field.
   * @param value the value to set.
   */
  public void setReason(java.lang.String value) {
    this.reason = value;
  }

  /**
   * Creates a new ResultOfCheckingEvent RecordBuilder.
   * @return A new ResultOfCheckingEvent RecordBuilder
   */
  public static org.example.events.ResultOfCheckingEvent.Builder newBuilder() {
    return new org.example.events.ResultOfCheckingEvent.Builder();
  }

  /**
   * Creates a new ResultOfCheckingEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ResultOfCheckingEvent RecordBuilder
   */
  public static org.example.events.ResultOfCheckingEvent.Builder newBuilder(org.example.events.ResultOfCheckingEvent.Builder other) {
    if (other == null) {
      return new org.example.events.ResultOfCheckingEvent.Builder();
    } else {
      return new org.example.events.ResultOfCheckingEvent.Builder(other);
    }
  }

  /**
   * Creates a new ResultOfCheckingEvent RecordBuilder by copying an existing ResultOfCheckingEvent instance.
   * @param other The existing instance to copy.
   * @return A new ResultOfCheckingEvent RecordBuilder
   */
  public static org.example.events.ResultOfCheckingEvent.Builder newBuilder(org.example.events.ResultOfCheckingEvent other) {
    if (other == null) {
      return new org.example.events.ResultOfCheckingEvent.Builder();
    } else {
      return new org.example.events.ResultOfCheckingEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ResultOfCheckingEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ResultOfCheckingEvent>
    implements org.apache.avro.data.RecordBuilder<ResultOfCheckingEvent> {

    private org.example.events.TransactionStatusAvro status;
    private java.lang.String transactionNumber;
    private java.lang.String reason;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.example.events.ResultOfCheckingEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.status)) {
        this.status = data().deepCopy(fields()[0].schema(), other.status);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.transactionNumber)) {
        this.transactionNumber = data().deepCopy(fields()[1].schema(), other.transactionNumber);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.reason)) {
        this.reason = data().deepCopy(fields()[2].schema(), other.reason);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ResultOfCheckingEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(org.example.events.ResultOfCheckingEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.status)) {
        this.status = data().deepCopy(fields()[0].schema(), other.status);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.transactionNumber)) {
        this.transactionNumber = data().deepCopy(fields()[1].schema(), other.transactionNumber);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.reason)) {
        this.reason = data().deepCopy(fields()[2].schema(), other.reason);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public org.example.events.TransactionStatusAvro getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public org.example.events.ResultOfCheckingEvent.Builder setStatus(org.example.events.TransactionStatusAvro value) {
      validate(fields()[0], value);
      this.status = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public org.example.events.ResultOfCheckingEvent.Builder clearStatus() {
      status = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'transactionNumber' field.
      * @return The value.
      */
    public java.lang.String getTransactionNumber() {
      return transactionNumber;
    }


    /**
      * Sets the value of the 'transactionNumber' field.
      * @param value The value of 'transactionNumber'.
      * @return This builder.
      */
    public org.example.events.ResultOfCheckingEvent.Builder setTransactionNumber(java.lang.String value) {
      validate(fields()[1], value);
      this.transactionNumber = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionNumber' field has been set.
      * @return True if the 'transactionNumber' field has been set, false otherwise.
      */
    public boolean hasTransactionNumber() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'transactionNumber' field.
      * @return This builder.
      */
    public org.example.events.ResultOfCheckingEvent.Builder clearTransactionNumber() {
      transactionNumber = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'reason' field.
      * @return The value.
      */
    public java.lang.String getReason() {
      return reason;
    }


    /**
      * Sets the value of the 'reason' field.
      * @param value The value of 'reason'.
      * @return This builder.
      */
    public org.example.events.ResultOfCheckingEvent.Builder setReason(java.lang.String value) {
      validate(fields()[2], value);
      this.reason = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'reason' field has been set.
      * @return True if the 'reason' field has been set, false otherwise.
      */
    public boolean hasReason() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'reason' field.
      * @return This builder.
      */
    public org.example.events.ResultOfCheckingEvent.Builder clearReason() {
      reason = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ResultOfCheckingEvent build() {
      try {
        ResultOfCheckingEvent record = new ResultOfCheckingEvent();
        record.status = fieldSetFlags()[0] ? this.status : (org.example.events.TransactionStatusAvro) defaultValue(fields()[0]);
        record.transactionNumber = fieldSetFlags()[1] ? this.transactionNumber : (java.lang.String) defaultValue(fields()[1]);
        record.reason = fieldSetFlags()[2] ? this.reason : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ResultOfCheckingEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ResultOfCheckingEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ResultOfCheckingEvent>
    READER$ = (org.apache.avro.io.DatumReader<ResultOfCheckingEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeEnum(this.status.ordinal());

    out.writeString(this.transactionNumber);

    if (this.reason == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.reason);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.status = org.example.events.TransactionStatusAvro.values()[in.readEnum()];

      this.transactionNumber = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.reason = null;
      } else {
        this.reason = in.readString();
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.status = org.example.events.TransactionStatusAvro.values()[in.readEnum()];
          break;

        case 1:
          this.transactionNumber = in.readString();
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.reason = null;
          } else {
            this.reason = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










