/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.example.events;
@org.apache.avro.specific.AvroGenerated
public enum TransactionStatusAvro implements org.apache.avro.generic.GenericEnumSymbol<TransactionStatusAvro> {
  ACCEPTED, BLOCKED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TransactionStatusAvro\",\"namespace\":\"org.example.events\",\"symbols\":[\"ACCEPTED\",\"BLOCKED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
